<Project Sdk="Aspire.AppHost.Sdk/13.6.0">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AspireUseCliBundle>true</AspireUseCliBundle>
    <UserSecretsId>e0fe327c-fddb-46c9-ae3c-f8f1ddd64c68</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.SqlServer" />
    <PackageReference Include="CommunityToolkit.Aspire.Hosting.MailPit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Spike.Api\Spike.Api.csproj" />
  </ItemGroup>

</Project>
