<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MailKit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Spike.Users.Contracts\Spike.Users.Contracts.csproj" />
  </ItemGroup>

</Project>
