<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Mediator.Abstractions" />
    <PackageReference Include="MailKit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Spike.Contracts\Spike.Contracts.csproj" />
  </ItemGroup>

</Project>
